name: Package & Website Deploy

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15

      - name: Install Dependencies
        run: npm ci

      - name: Lint Project
        run: npm run lint

      - name: Test Project
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm run publish:npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm ci

      - name: Publish to GitHub Packages
        run: npm run publish:gh
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PAT}}

  deploy-website:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15

      - name: Install Dependencies
        run: |
          npm ci
          cd website
          npm ci

      - name: Deploy to GitHub Pages
        run: |
          cd website
          npm run deploy
        env:
          GIT_USER: YashTotale
          GIT_PASS: ${{secrets.GH_PAT}}
          USE_SSH: false
