name: Package & Website Deploy

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15

      - name: Install Dependencies
        run: npm ci

      - name: Lint Project
        run: npm run lint

      - name: Check Links
        run: npm run check-links

      - name: Test Project
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm run publish:npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm ci

      - name: Publish to GitHub Packages
        run: npm run publish:gh
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PAT}}

  deploy-website:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15

      - name: Install Dependencies
        run: |
          npm ci
          cd website
          npm ci

      - name: Add Deploy Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Deploy to GitHub Pages
        run: |
          cd website
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          npm run deploy
        env:
          GIT_USER: git
          USE_SSH: true
